### ISSUE TITLE
Incomplete abstract

### ISSUE THREAD

**Issue by IcanMorris** [zpoon/runescape-wiki-reddit#2]
The abstract of "The needle skips" isn't fully displayed. In contrast, "Violet is blue" works as expected.
Might be a wiki issue, but at first glance I didn't see anything obvious in the wiki source:

https://www.reddit.com/r/runescape/comments/ak15ou/quest_calculator/ef0vatk/

**Comment by zpoon** [comment]
Looks like the wiki has special props when it needs to modify the sorting of pages with stuff like "The" in them, so the bot's grabbing the wrong info at the location it expects it to be.

Added a check to make sure it's grabbing the "description" prop type. Fixed in d97dde621c115b12e62ecc8055e2f70f36dc5877

Thanks again!
